openapi: 3.0.3
info:
  title: Swagger - OpenAPI 3.0
  version: 1.0.0
paths:
  /users:
    get:
      description: Get all users
      responses:
        '200':
          description: Gets an array on users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string